version: '3.1'

services:

  db:
    container_name: mysql-8.0.30
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rustPassWord 
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --requirepass root
    ports:
      - 6379:6379

  adminer:
    container_name: admin-mysql
    image: adminer 
    restart: always
    ports:
      - 8080:8080
      